# .github/workflows/tagpr.yml
name: tagpr

on:
  push:
    branches: ["main"]

# このワークフロー自体に必要な権限
permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install stable
        run: |
          rustup toolchain install stable --profile minimal --component rustfmt,clippy
          rustup default stable
      - name: Run tagpr
        id: tagpr
        uses: Songmu/tagpr@v1.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


